name: build-macos
on:
  push:
    branches: [ dev-v1 ]
  pull_request:
    branches: [ dev-v1 ]

jobs:
  build-macos:
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: install-libs
    #  run: sudo apt-get install liblldb-9-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
    - name: configure
      run: export CC=clang && export CXX=clang++ && mkdir ${GITHUB_WORKSPACE}/build && cd ${GITHUB_WORKSPACE}/build && cmake ..
    - name: build
      run: cmake --build ${GITHUB_WORKSPACE}/build -v
