---
name: ci-linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build | ${{ matrix.distro.name }} - ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    timeout-minutes: 45

    container:
      image: ${{ matrix.distro.image }}

    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        compiler: [gcc, clang]
        distro:
          - { name: debian-bullseye, image: debian:11, needs_cmake: "true" }
          - { name: debian-bookworm, image: debian:12, needs_cmake: "false" }
          - { name: ubuntu-jammy, image: ubuntu:22.04, needs_cmake: "true" }
          - { name: ubuntu-noble, image: ubuntu:24.04, needs_cmake: "false" }

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # run our custom github action for setting up the lldbg build environment
      - uses: ./.github/actions/setup-linux-build-container
        with:
          compiler: ${{ matrix.compiler }}
          update_cmake: ${{ matrix.distro.needs_cmake }}

      - name: Configure
        shell: bash
        run: cmake --preset ci

      - name: Build
        run: cmake --build --preset ci
